name: deploy

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "privacy-scaling-explorations/maci"
          ref: "dev"
          path: "maci"

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: |
          cd maci
          pnpm install --frozen-lockfile --prefer-offline

      - name: Dwonload Test Proving Keys
        run: |
          cd maci
          pnpm download-zkeys:test

      - name: Build
        run: |
          mv ${{ github.workspace }}/config/hardhat.config.ts maci/contracts/hardhat.config.ts

          cd maci
          pnpm build


      - name: Deploy MACI Contracts
        run: |
          mv ${{ github.workspace }}/config/deploy-config.json maci/contracts/deploy-config.json

          cd maci/contracts
          pnpm deploy:sepolia
        env:
          ETH_SK: ${{ secrets.ETH_SK }}
          SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}

      - name: Deploy MACI Contracts
        run: |
          cd maci/contracts
          pnpm deploy-poll:sepolia
        env:
          ETH_SK: ${{ secrets.ETH_SK }}
          SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}


